site_name: ATLAS Open Data Guide 2019
repo_url: 'https://github.com/veritasalice/ATLASOpenDataGuide'
# Contents
nav:
    - Home: 'index.md'
    - About ATLAS experiment:
      - ATLAS experiment: 'atlas/experiment.md'
      - ATLAS events: 'atlas/atlas_events.md'
      - Higgs boson: 'atlas/the-higgs-boson.md'
      - ATLAS glossary: 'atlas/GLOSSARY.md'
      - Particle physics masterclasses: 'atlas/particle-physics-masterclasses.md'
    - Datasets:
      - Data and Simulated Data: 'datasets/data-and-simulated-data.md'
      - 8 TeV dataset: 'datasets/dataset8.md'
      - 13 TeV dataset: 'datasets/dataset13.md'
    - Data Visualization:
      - Data visualization: 'visualization/index.md'
      - Finding the Higgs: 'visualization/find_the_higgs_2.md'
      - Histogram analyser 1: 'visualization/histogram-analyser-1.md'
      - Application 1: 'visualization/app1.md'
      - Histogram analyser 2: 'visualization/histogram-analyser-2.md'
      - Application 2: 'visualization/app2.md'
      - Separate signals: 'separate_signals.md'
    - Frameworks:
      - C++ framework for 13 TeV dataset: 'frameworks/cpp.md'
      - Python framework for 8 TeV dataset: 'frameworks/python.md'
    - Notebooks:
      - Analysis examples: 'notebooks/analysis-examples.md'
      - Framework interface: 'notebooks/framework-interface.md'
    - Virtual Machine: 'vm/index.md'
    - How to contribute to this documentation?: 'documentation/document.md'

# Theme
theme:
  name: null
  custom_dir: 'material'
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/outline_80_white.png"
  feature:
    tabs: true
  static_templates:
    - 404.html
  favicon: 'assets/images/favicon.ico'
  search_index_only: true
